package com.cpf.mapper.transaction;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.cpf.beans.transaction.TraBidrecord;

public interface TraBidrecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_bidrecord
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String recordid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_bidrecord
     *
     * @mbggenerated
     */
    int insert(TraBidrecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_bidrecord
     *
     * @mbggenerated
     */
    int insertSelective(TraBidrecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_bidrecord
     *
     * @mbggenerated
     */
    TraBidrecord selectByPrimaryKey(String recordid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_bidrecord
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TraBidrecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_bidrecord
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TraBidrecord record);
    
    /**
     * 根据拍品的id查询出家记录
     */
    List<TraBidrecord> selectBidRecordByProductId(@Param("productId") String productId,
    		@Param("beginIndex") int beginIndex,@Param("size") int size);
    int selectBidRecordByProductIdCount(@Param("productId") String productId);
}