package com.cpf.mapper.transaction;

import org.apache.ibatis.annotations.Param;
import java.util.List;
import com.cpf.beans.transaction.TraProductFiles;

public interface TraProductFilesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_product_files
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String filesid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_product_files
     *
     * @mbggenerated
     */
    int insert(TraProductFiles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_product_files
     *
     * @mbggenerated
     */
    int insertSelective(TraProductFiles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_product_files
     *
     * @mbggenerated
     */
    TraProductFiles selectByPrimaryKey(String filesid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_product_files
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TraProductFiles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tra_product_files
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TraProductFiles record);
    
    /**
     * 根据品种id查询商品的图片列表
     */
    List<TraProductFiles> selectPicByProductionId(@Param("productId")String productId);
}