package com.cpf.beans.system;

import java.util.Date;

public class SysNews {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_news.newsid
	 * @mbggenerated
	 */
	private String newsid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_news.newcontent
	 * @mbggenerated
	 */
	private String newcontent;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_news.sendtime
	 * @mbggenerated
	 */
	private Date sendtime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_news.newstype
	 * @mbggenerated
	 */
	private String newstype;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_news.tradingid
	 * @mbggenerated
	 */
	private String tradingid;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_news.newsid
	 * @return  the value of sys_news.newsid
	 * @mbggenerated
	 */
	public String getNewsid() {
		return newsid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_news.newsid
	 * @param newsid  the value for sys_news.newsid
	 * @mbggenerated
	 */
	public void setNewsid(String newsid) {
		this.newsid = newsid == null ? null : newsid.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_news.newcontent
	 * @return  the value of sys_news.newcontent
	 * @mbggenerated
	 */
	public String getNewcontent() {
		return newcontent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_news.newcontent
	 * @param newcontent  the value for sys_news.newcontent
	 * @mbggenerated
	 */
	public void setNewcontent(String newcontent) {
		this.newcontent = newcontent == null ? null : newcontent.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_news.sendtime
	 * @return  the value of sys_news.sendtime
	 * @mbggenerated
	 */
	public Date getSendtime() {
		return sendtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_news.sendtime
	 * @param sendtime  the value for sys_news.sendtime
	 * @mbggenerated
	 */
	public void setSendtime(Date sendtime) {
		this.sendtime = sendtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_news.newstype
	 * @return  the value of sys_news.newstype
	 * @mbggenerated
	 */
	public String getNewstype() {
		return newstype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_news.newstype
	 * @param newstype  the value for sys_news.newstype
	 * @mbggenerated
	 */
	public void setNewstype(String newstype) {
		this.newstype = newstype == null ? null : newstype.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_news.tradingid
	 * @return  the value of sys_news.tradingid
	 * @mbggenerated
	 */
	public String getTradingid() {
		return tradingid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_news.tradingid
	 * @param tradingid  the value for sys_news.tradingid
	 * @mbggenerated
	 */
	public void setTradingid(String tradingid) {
		this.tradingid = tradingid == null ? null : tradingid.trim();
	}
}